- name: Group Policy - Check
  hosts: management
  vars_files:
    - vars/var-gpo.yml
  vars:
    ansible_winrm_transport: kerberos
  vars_prompt:
    - name: domainSelection
      prompt: |
        Select target domain:
        {% for domain in domains %}
        {{ loop.index }}. {{ domain.name }} - {{ domain.fqdn }}
        {% endfor %}
        Enter number
      private: false
    - name: ansible_user
      prompt: "Admin username (e.g. administrator@JOELOVELESS.COM)"
      private: false
    - name: ansible_password
      prompt: "Password"
      private: true
    - name: gpoName
      prompt: What is the name of the GPO to check?
      private: false

  tasks:
    - name: Set target domain from selection
      ansible.builtin.set_fact:
        targetDomain: "{{ domains[domainSelection | int - 1].fqdn }}"
        
    - name: Check GPO prerequisites
      ansible.builtin.include_tasks: tasks/task-check-gpo-prerequisites.yml

    - name: Check if GPO exists
      ansible.builtin.include_tasks: tasks/task-check-gpo-exists.yml
