# Assigns permissions to a GPO based on the permissions and AD group defined in the var-gpo.yml file.
---
- name: Group Policy - Assign Permissions
  hosts: group_policy
  vars_files:
    - vars/var-gpo.yml
  vars:
    ansible_user: "{{ username_input }}@{{ domains[domainSelection | int - 1].fqdn | upper }}"
  vars_prompt:
    - name: domainSelection
      prompt: |
        Select target domain:
        {% for domain in domains %}
        {{ loop.index }}. {{ domain.name }} - {{ domain.fqdn }}
        {% endfor %}
        Enter number
      private: false
    - name: username_input
      prompt: "Username"
      private: false
    - name: ansible_password
      prompt: "Password"
      private: true
    - name: gpoName
      prompt: Enter the GPO name
      private: false

  tasks:
    - name: Set target domain from selection
      ansible.builtin.set_fact:
        targetDomain: "{{ domains[domainSelection | int - 1].fqdn }}"
        targetDC: "{{ domains[domainSelection | int - 1].dc }}"
        group: "{{ domains[domainSelection | int - 1].group }}"
        groupPermissions: "{{ domains[domainSelection | int - 1].groupPermissions }}"

    - name: Check GPO prerequisites
      ansible.builtin.include_tasks: tasks/task-check-gpo-prerequisites.yml

    - name: Check if GPO exists
      ansible.builtin.include_tasks: tasks/task-check-gpo-exists.yml

    - name: Check and set GPO permissions
      ansible.builtin.include_tasks: tasks/task-check-and-set-gpo-permissions.yml
