[libdefaults]
        forwardable = true
        default_realm = JOELOVELESS.COM
        dns_lookup_realm = false
        dns_lookup_kdc = false

# The following krb5.conf variables are only for MIT Kerberos.
        kdc_timesync = 1
        ccache_type = 4
        forwardable = true
        proxiable = true

[realms]


        JOELOVELESS.COM = {
                kdc = DC01.JOELOVELESS.COM
                admin_server = DC01.JOELOVELESS.COM
                kpasswd_server = DC01.JOELOVELESS.COM
                #default_domain = domain.com
                default_domain = JOELOVELESS.COM
                }


[domain_realm]

         .joeloveless.com = JOELOVELESS.COM
         joeloveless.com = JOELOVELESS.COM
