- name: Group Policy - Check
  hosts: group_policy
  vars:
    ansible_user: "{{ username_input }}@{{ domains[0].fqdn | upper }}"
  vars_prompt:
    - name: username_input
      prompt: "Admin username"
      private: false
    - name: ansible_password
      prompt: "Password"
      private: true
    - name: gpoName
      prompt: What is the name of the GPO to check?
      private: false

  tasks:
    - name: Set target domain
      ansible.builtin.set_fact:
        targetDomain: "{{ domains[0].fqdn }}"
        targetDC: "{{ domains[0].dc }}"
        
    - name: Check GPO prerequisites
      ansible.builtin.include_tasks: tasks/task-check-gpo-prerequisites.yml

    - name: Check if GPO exists
      ansible.builtin.include_tasks: tasks/task-check-gpo-exists.yml
      vars:
        gpoMustExist: false
