- name: Group Policy - Link
  hosts: group_policy
  vars_files:
    - vars/var-gpo.yml
  vars:
    ansible_user: "{{ username_input }}@{{ domains[0].fqdn | upper }}"
  vars_prompt:
    - name: username_input
      prompt: "Admin username"
      private: false
    - name: ansible_password
      prompt: "Password"
      private: true
    - name: gpoName
      prompt: Enter the GPO name
      private: false

  tasks:
    - name: Set target domain
      ansible.builtin.set_fact:
        targetDomain: "{{ domains[0].fqdn }}"
        targetDC: "{{ domains[0].dc }}"
        backupPath: "{{ domains[0].backupPath }}"
        ous: "{{ domains[0].ous }}"

# MAIN
    - name: Check GPO prerequisites
      ansible.builtin.include_tasks: tasks/task-check-gpo-prerequisites.yml

    - name: Check if GPO exists
      ansible.builtin.include_tasks: tasks/task-check-gpo-exists.yml

    - name: Check and link GPO to each OU
      ansible.builtin.include_tasks: tasks/task-check-and-link-gpo.yml
      loop: "{{ ous }}"
      loop_control:
        label: "{{ item.name }}"