domains:
  - name: "Joe Loveless"
    fqdn: "joeloveless.com"
    backupPath: 'C:\Windows\Temp\GPOBackup\joeloveless.com'
    ous:
      - name: "Windows 11 Workstations"
        dn: "OU=Windows_11,OU=JoeLoveless_Workstations,DC=joeloveless,DC=com"
      - name: "Windows 10 Workstations"
        dn: "OU=Windows_10,OU=JoeLoveless_Workstations,DC=joeloveless,DC=com"
# - name: "Second Domain"
#   fqdn: "seconddomain.com"
#   ous:
#     - name: "Windows 11 Workstations"
#       dn: "OU=Windows_11,OU=Workstations,DC=seconddomain,DC=com"